# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_auto_20170616_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bigbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=45)),
                ('in_print', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.Author')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
